apiVersion: batch/v1
kind: Job
metadata:
  name: checkpoint-translation
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: loggen
          image: rock1017/checkpoint-migration:1.0.0
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
          env:
            - name: CONTAINER_LOG_PATH_FLUENTD
              value: "/var/log/splunk-fluentd-containers.log.pos"
            - name: CONTAINER_LOG_PATH_OTEL
              value: "/var/lib/otel_pos/receiver_filelog_"
            - name: CUSTOM_LOG_PATH_FLUENTD
              value: "/var/log/splunk-fluentd-*.pos"
            - name: CUSTOM_LOG_PATH_OTEL
              value: "/var/lib/otel_pos/receiver_filelog_"
            - name: JOURNALD_LOG_PATH_FLUENTD
              value: "splunkd-fluentd-journald-*.pos.json"
            - name: JOURNALD_LOG_PATH_OTEL
              value: "/var/lib/otel_pos/receiver_journald_"
          resources:
            limits:
              cpu: 128m
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibotelpos
              mountPath: /var/lib/otel_pos
        volumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibotelpos
            hostPath:
              path: /var/lib/otel_pos
